### PR TITLE
Mentorship Subscription-related fixes

### LINKED ISSUE #125: App crash when going to Student Dashboard > Mentorship Contracts > View row
55BA5DD3-D56A-4348-AE1E-7EF3E7295417
7D77139B-5507-43D2-A041-2EDBDEAF9ED6
D6A4C9DA-A52C-473C-9C44-2D8C382B74A6

### PR DESCRIPTION
**Pull request by natalieloke**
# Issue
Fixes #125 and some other misc related stuff
- main problem was because the object wasn't returned yet when the child components rendered
- added some comment placeholders to indicate what component it previously used

# Changelog:
- see commit log

## Checklist:

- [x] Merged latest develop
- [x] PR title makes sense

## Screenshots (where relevant):
**Mentorship Contracts Table Responsiveness**
Screenshot 2021-04-08 at 10 47 58 PM
Screenshot 2021-04-08 at 10 47 52 PM
Screenshot 2021-04-08 at 10 47 45 PM
Screenshot 2021-04-08 at 10 47 36 PM

### CODE REVIEW

File: src/pages/student/mentorships/subscription/index.js [hunk 1]
```diff
@@ -1,12 +1,90 @@
...
+          setMentorshipListing(result.contract.MentorshipListing)
+        }
+      }
+    }
+
+    getMentorshipSubscription()
+  }, [id])
+
+  console.log('mentorshipSubscription is ', mentorshipSubscription) // Nat to deal with this in a later PR to populate the page with more subscription specific deets
+
```
Comment (natalieloke) [inline src/pages/student/mentorships/subscription/index.js:33]: this console log is needed as a placeholder to use mentorshipSubscription (currently not used, but will be used in future PRs)

**Review by rawrrencee — APPROVED** [review]
看好至我！
